config/routes.rb
Rails.application.routes.draw do
  get 'deals/index'

  get 'deals/show'

  get 'deals/new'

end

app/models/deal.rb
class Deal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
    def index
      deal = HTTParty.get('http://api.popshops.com/v3/deals.json?account=etl4xy4bqez70idzyypjwyfxn&catalog=dxeqyv83t3vcox7iztg9ufg16')
      @description = deal['results']['deals']['deal'][0]['description']
      @name = deal['results']['deals']['deal'][0]['name']
      @restrictions = deal['results']['deals']['deal'][0]['restrictions']
    end


    def show
     @deal = Deal.find(params[:id])
    end


    def new
     @deal = Deal.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/deals/index.html.erb
<h1>Example Deals Page </h1>
<!-- <p>Find me in app/views/deals/index.html.erb</p> -->

<h2> Deals </h2>
<h3>New Deal From:</h3>
<p><%= @description %></p></br>
<h3>The Deal: </h3>
<p><%= @name %></p></br>
<h3>Other info: </h3>
<p><%= @restrictions %></p>

app/views/deals/new.html.erb
<h1>Deals#new</h1>
<p>Find me in app/views/deals/new.html.erb</p>

app/views/deals/show.html.erb
<h1>Deals#show</h1>
<p>Find me in app/views/deals/show.html.erb</p>

<h1> Deal </h1>
<h2><%= @deal.title  %></h2>
<h3><%= @deal.description %></h2>
<p><%= @deal.number %></p>
<p><%= @deal.price %></p>

<%= link_to 'Back', deals_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Item</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>